default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: LMS_db
  password: LMS@2004
  host: freshworks-batch-2.c52o448usuop.ap-south-1.rds.amazonaws.com
development:
  <<: *default
  database: b2_prod_lms
test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
